### ISSUE TITLE
Create Java class for managing the server socket and server commands

### ISSUE THREAD

**Issue by lentidas** [lentidas/DAI-2425-PW2#5]
# Definition of done

## Hard requirements

- [x] Create Java class for the the server socket creation and management
- [x] Manage the subcommands possible for the our protocol specification
- [x] Add support for multithreading to support multiple client connections
- [x] Instantiate the class that manages the game logic and where its respective game variables will be stored for the current game session
- [x] List available game commands inside the class or get it from the game logic package

**Comment by lentidas** [comment]
I've reopened the issue because the work is not complete for this 😊

**Comment by PedroAS7** [comment]
> I've reopened the issue because the work is not complete for this 😊

Weird, I don't remember closing it. PR #14 available for review

**Comment by lentidas** [comment]
> > I've reopened the issue because the work is not complete for this 😊
> 
> Weird, I don't remember closing it. PR #14 available for review

It was closed automatically, because there was a PR connected to it, so it closes automatically when the PR is merged 😉
